using Network.Server.Common;
using Network.Server.Common.Utils;
using Network.Server.Front.Actor;
using Network.Server.Front.Config;
using Network.Server.Front.Core;
using Network.Server.Generated;
using NetworkEngine.Tests.Node.Controller;
using NetworkServer.ProtoAutoGen;
using NetworkServer.ProtoGenerator;
using Serilog;
using Serilog.Events;
using Xunit.Abstractions;

namespace NetworkEngine.Tests.Node;

public class TestServerFactory(string redisConnectionString = "localhost:6379") : IAsyncDisposable
{
    private readonly List<IHost> _hosts = [];
    private readonly Dictionary<long, FrontServer> _servers = [];
    private static int _portIndex = 5001;

    private static readonly ProtoInitializer Init = new AutoGeneratedInitializer();

    public async Task<FrontServer> CreateNodeAsync(ITestOutputHelper? output = null)
    {
        Init.Initialize();

        try
        {
            var hostBuilder = Host.CreateDefaultBuilder()
                .UseServiceProviderFactory(new DefaultServiceProviderFactory(new ServiceProviderOptions
                {
                    ValidateOnBuild = true  // 빌드 시 모든 싱글톤 즉시 생성
                }))
                .UseSerilog((context, services, configuration) =>
                {
                    configuration.MinimumLevel.Debug();

                    // xUnit 출력으로 로그 전송
                    if (output != null)
                    {
                        configuration.WriteTo.TestOutput(output, LogEventLevel.Debug,
                            outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}");
                    }   
                })
                .ConfigureServices(services =>
                {
                    services.AddHostedService<FrontServer>();
                    // 클러스터 핵심 서비스만 등록
                    services.AddSingleton<UniqueIdGenerator>(_ => new UniqueIdGenerator(Guid.NewGuid()));
                    services.AddSingleton<IApplicationStopper, HostApplicationStopper>();
                    services.AddSingleton<IInGameConnectionQueue, InGameConnectionQueue>();
                    services.AddSingleton<TimeProvider>(_ => TimeProvider.System);
                    services.AddHandler();
                    services.AddSingleton<IActorManager, ActorManager>();
                    services.AddSingleton<TestController>();

                    services.Configure<FrontServerConfig>(options =>
                    {
                        options.Address = "localhost";
                        options.Port = 1400;
                    });

                });

            var host = await hostBuilder.StartAsync();
            var server = host.Services.GetRequiredService<FrontServer>();
            _hosts.Add(host);
            return server;
        }
        catch (Exception e)
        {
            output?.WriteLine(e.ToString());
            throw;
        }
    }

    public async ValueTask DisposeAsync()
    {
        foreach (var host in _hosts)
        {
            await host.StopAsync();
            host.Dispose();
        }

        _hosts.Clear();
        _servers.Clear();
    }
}

