using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using Google.Protobuf;
using Network.Server.Common.Memory;
using Network.Server.Common.Packets;
using Network.Server.Common.Utils;
using NetworkServer.ProtoGenerator;

namespace NetworkClient.Network
{
	public sealed class ProtoPacketParser : IPacketParser<(Header header, IMessage message)>
	{
		private readonly Lz4 _lz4 = new();
		private IMessage? GetMessage(int msgId, ReadOnlySpan<byte> span)
		{
			var parser = AutoGeneratedParsers.GetParserById(msgId);
			return parser?.ParseFrom(span);
		}

		public IReadOnlyList<(Header header, IMessage message)> Parse(ArrayPoolBufferWriter buffer)
		{
			var packets = new List<(Header, IMessage)>(10);

			while (true)
			{
				// 1. Peek bodySize (BigEndian)
				var span = buffer.WrittenSpan;
				if (span.Length < 4)
					break;

				int totalSize = BinaryPrimitives.ReadInt32BigEndian(span);
				if (buffer.WrittenCount < totalSize)
					break;

				// 3. Consume actual packet using BigEndian reads
				buffer.ReadAdvance(4); // bodySize

				var header = new Header
				{
					Flags = (PacketFlags)buffer.ReadByte(),
					MsgId = buffer.ReadInt32BigEndian(),
					MsgSeq = buffer.ReadUInt16BigEndian()
				};

				if (header.Flags.HasFlagFast(PacketFlags.HasError))
				{
					header.ErrorCode = buffer.ReadUInt16BigEndian();
				}


				IMessage? message;

				if (header.Flags.HasFlagFast(PacketFlags.Compressed))
				{
					header.OriginalSize = buffer.ReadInt32BigEndian();
					var compressSize = totalSize - header.GetSize();
					var body = _lz4.Decompress(buffer.WrittenSpan.Slice(0, compressSize), header.OriginalSize);
					buffer.ReadAdvance(compressSize);

					message = GetMessage(header.MsgId, body);
				}
				else
				{
					var payloadSize = totalSize - header.GetSize();
					message = GetMessage(header.MsgId, span.Slice(0, payloadSize));
					buffer.ReadAdvance(payloadSize);
				}

				if (message == null)
				{
					return [];
				}

				packets.Add((header, message));
			}

			return packets;
		}
	}
}
