using System;
using System.Buffers;
using System.Buffers.Binary;
using System.Collections.Generic;
using Google.Protobuf;
using Network.Server;
using Network.Server.Common.Memory;
using Network.Server.Common.Packets;
using NetworkServer.ProtoGenerator;

namespace NetworkClient.Network
{
    public class NetworkPacket
    {
        public NetworkPacket(Header header, IMessage message)
        {
            Header = header;
            Message = message;
        }

        public Header Header { get; init; }
        public IMessage Message { get; init; }
    }

    public sealed class ProtoPacketParser : IPacketParser<NetworkPacket>
    {
        public IReadOnlyList<NetworkPacket> Parse(ArrayPoolBufferWriter buffer)
        {
            var packets = new List<NetworkPacket>();

            while (true)
            {
                // 1. Peek bodySize (LittleEndian)
                var span = buffer.WrittenSpan;
                if (span.Length < 4)
                    break;

                int totalSize = BinaryPrimitives.ReadInt32LittleEndian(span);
                if (buffer.WrittenCount < totalSize)
                    break;

                if (0 >= totalSize || PacketDefine.MaxPacketSize <= totalSize)
                    throw new Exception($"Invalid Packet Length : {totalSize}");

                // 3. Consume actual packet using LittleEndian reads
                buffer.ReadAdvance(4); // bodySize

                var header = new Header
                {
                    Flags = (PacketFlags) buffer.ReadByte(),
                    MsgId = buffer.ReadInt32LittleEndian(),
                    MsgSeq = buffer.ReadUInt16LittleEndian(),
                    RequestId = buffer.ReadUInt16LittleEndian()
                };

                if (header.Flags.HasFlagFast(PacketFlags.HasError))
                {
                    header.ErrorCode = buffer.ReadUInt16LittleEndian();
                }

                IMessage? message;

                var parser = AutoGeneratedParsers.GetParserById(header.MsgId);
                if (parser == null)
                    throw new Exception($"Unknown packet ID: {header.MsgId}");

                if (header.Flags.HasFlagFast(PacketFlags.Compressed))
                {
                    header.OriginalSize = buffer.ReadInt32LittleEndian();
                    var compressSize = totalSize - header.GetSize();
                    message = ProtobufCompressor.DecompressMessage(parser, buffer.WrittenSpan.Slice(0, compressSize), header.OriginalSize);
                    buffer.ReadAdvance(compressSize);
                }
                else
                {
                    var payloadSize = totalSize - header.GetSize();
                    message = parser.ParseFrom(buffer.GetReadSpan(payloadSize));
                    buffer.ReadAdvance(payloadSize);
                }

                if (message == null)
                    throw new InvalidCastException($"Cannot cast MsgId:{header.MsgId} to {nameof(NetworkPacket)}");

                packets.Add(new NetworkPacket(header, message));
            }

            return packets;
        }
    }
}