using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PacketParserGenerator
{
    /// <inheritdoc />
    [Generator]
    public class ParserGenerator : IIncrementalGenerator
    {
        /// <inheritdoc />
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. IMessage 구현체 찾기
            var protoTypes = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) => IsCandidateClass(s),
                    transform: (ctx, _) => GetProtoModel(ctx))
                .Where(m => m != null);

            // 2. 소스 생성 실행 (모든 타입을 모아서 한 번에 처리)
            context.RegisterSourceOutput(protoTypes.Collect(), Execute);
        }

        private bool IsCandidateClass(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax;
        }

        private ProtoModel GetProtoModel(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (symbol == null) return null;

            // Google.Protobuf.IMessage 인터페이스 확인
            var isProtoMessage = symbol.AllInterfaces.Any(i => i.ToDisplayString().StartsWith("Google.Protobuf.IMessage"));
            
            // Parser 프로퍼티가 있는지 확인 (실제 Protobuf 생성 클래스인지 검증)
            var hasParser = symbol.GetMembers("Parser").Any(m => m.Kind == SymbolKind.Property && m.IsStatic);

            if (isProtoMessage && hasParser)
            {
                return new ProtoModel(
                    symbol.ContainingNamespace.ToDisplayString(),
                    symbol.Name,
                    symbol.ToDisplayString()
                );
            }

            return null;
        }

        private void Execute(SourceProductionContext context, ImmutableArray<ProtoModel> protoTypes)
        {
            if (protoTypes.IsDefaultOrEmpty)
            {
                context.AddSource("AutoGeneratedInitializer.g.cs", SourceText.From(
                    "// No protobuf types found. Check if .proto files are compiled before Source Generator runs.",
                    Encoding.UTF8));
                return;
            }

            // 중복 제거 및 정렬
            var distinctTypes = protoTypes
                .Distinct() // ProtoModel Equals/GetHashCode 필요 (Class면 별도 Comparer 필요하나, 간단히 생략하거나 DistinctBy 사용)
                .OrderBy(t => t.Namespace)
                .ThenBy(t => t.ClassName)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This code was generated by ProtobufParserGenerator");
            sb.AppendLine($"// Found {distinctTypes.Count} protobuf types");
            sb.AppendLine("// AOT Compatible - No Reflection");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using NetworkServer.ProtoGenerator;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();

            // 네임스페이스별 그룹화
            var protoGroups = distinctTypes
                .GroupBy(t => t.Namespace)
                .OrderBy(g => g.Key)
                .ToList();

            // 1. 각 네임스페이스별 MsgId 확장 (partial class)
            foreach (var (group, protoIndex) in protoGroups.Select((g, i) => (g, i + 1)))
            {
                var namespaceName = group.Key;

                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");

                var sortedTypes = group.OrderBy(t => t.ClassName).ToList();

                foreach (var (type, messageIndex) in sortedTypes.Select((t, i) => (t, i)))
                {
                    int finalId = protoIndex * 100_000 + messageIndex;

                    sb.AppendLine($"    /// <summary>");
                    sb.AppendLine($"    /// {type.ClassName} 메시지 ID 확장");
                    sb.AppendLine($"    /// </summary>");
                    sb.AppendLine($"    public sealed partial class {type.ClassName}");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        /// <summary>");
                    sb.AppendLine($"        /// 메시지 ID (컴파일 타임 상수)");
                    sb.AppendLine($"        /// </summary>");
                    sb.AppendLine($"        public const int MsgId = {finalId};");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }

                sb.AppendLine("}");
                sb.AppendLine();
            }

            // 2. Initializer 클래스 생성
            sb.AppendLine("namespace NetworkServer.ProtoAutoGen");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 자동 생성된 프로토콜 초기화 클래스");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public class AutoGeneratedInitializer : NetworkServer.ProtoGenerator.ProtoInitializer");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 모든 프로토콜 파서를 등록합니다 (AOT 호환)");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public override void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (Initialized) return;");
            sb.AppendLine("            Initialized = true;");
            sb.AppendLine("            base.Initialize();");
            sb.AppendLine();

            foreach (var (group, protoIndex) in protoGroups.Select((g, i) => (g, i + 1)))
            {
                var namespaceName = group.Key;
                var sortedTypes = group.OrderBy(t => t.ClassName).ToList();

                foreach (var (type, messageIndex) in sortedTypes.Select((t, i) => (t, i)))
                {
                    
                    
                    sb.AppendLine($"            NetworkServer.ProtoGenerator.AutoGeneratedParsers.Register(");
                    sb.AppendLine($"                {type.FullName}.MsgId,");
                    sb.AppendLine($"                {type.FullName}.Parser,");
                    sb.AppendLine($"                {type.FullName}.Descriptor.FullName,");
                    sb.AppendLine($"                \"{namespaceName}\");");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// ModuleInitializer: 어셈블리 로드 시 자동으로 초기화를 수행합니다.");
            sb.AppendLine("        /// 사용자 코드에서 별도로 호출할 필요가 없습니다.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        [ModuleInitializer]");
            sb.AppendLine("        internal static void AutomaticInit()");
            sb.AppendLine("        {");
            sb.AppendLine("            new AutoGeneratedInitializer().Initialize();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("AutoGeneratedInitializer.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private class ProtoModel
        {
            public string Namespace { get; }
            public string ClassName { get; }
            public string FullName { get; }

            public ProtoModel(string @namespace, string className, string fullName)
            {
                Namespace = @namespace;
                ClassName = className;
                FullName = fullName;
            }

            // Distinct()를 위해 Equals 재정의
            public override bool Equals(object obj)
            {
                return obj is ProtoModel other && FullName == other.FullName;
            }

            public override int GetHashCode()
            {
                return FullName.GetHashCode();
            }
        }
    }
}