using Internal.Protocol;
using Network.Server.Common;
using Network.Server.Common.Packets;
using Network.Server.Common.Utils;
using Network.Server.Node.Cluster;
using Network.Server.Node.Config;
using Network.Server.Node.Core;
using Network.Server.Node.Extensions;
using Network.Server.Node.MessageRedisValueParser;
using Network.Server.Node.Network;
using Network.Server.Node.Utils;
using NetworkEngine.Tests.Node.Controller;
using NetworkServer.ProtoAutoGen;
using NetworkServer.ProtoGenerator;
using Serilog;
using Serilog.Events;
using Xunit.Abstractions;

namespace NetworkEngine.Tests.Node;

public record NetworkTestServer(
    NodeService Node,
    INodeManager NodeManager,
    INodeSender Sender) : IDisposable
{
    public void Dispose()
    {
        Node.Dispose();
    }
}

public class NodeTestServerFactory(string redisConnectionString = "localhost:6379") : IAsyncDisposable
{
    private readonly List<IHost> _hosts = [];
    private readonly Dictionary<string, List<NetworkTestServer>> _servers = [];
    private static int _portIndex = 5001;

    private static readonly ProtoInitializer Init = new AutoGeneratedInitializer();

    public async Task<NetworkTestServer> CreateNodeAsync(
        EServerType serverType,
        string apiName,
        ITestOutputHelper? output = null)
    {
        Init.Initialize();

        try
        {
            var hostBuilder = Host.CreateDefaultBuilder()
                .UseServiceProviderFactory(new DefaultServiceProviderFactory(new ServiceProviderOptions
                {
                    ValidateOnBuild = true  // 빌드 시 모든 싱글톤 즉시 생성
                }))
                .UseSerilog((context, services, configuration) =>
                {
                    configuration.MinimumLevel.Debug();
                    //configuration.Enrich.FromLogContext();

                    // xUnit 출력으로 로그 전송
                    if (output != null)
                    {
                        //configuration.WriteTo.TestOutput(output, LogEventLevel.Debug);
                        configuration.WriteTo.TestOutput(output, LogEventLevel.Debug,
                            outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}");
                    }   
                })
                .ConfigureServices(services =>
                {
                    // 클러스터 핵심 서비스만 등록
                    services.AddSingleton<NodeService>();
                    services.AddSingleton<UniqueIdGenerator>(_ => new UniqueIdGenerator(Guid.NewGuid()));
                    services.AddSingleton<IApplicationStopper, HostApplicationStopper>();
                    services.AddSingleton<IClusterRegistry, RedisClusterRegistry>();
                    services.AddSingleton<INodeManager, NodeManager>();
                    services.AddSingleton<IMessageRedisValueParser, JsonRedisValueParser>();
                    services.AddSingleton<RequestCache<InternalPacket>>(_ => new RequestCache<InternalPacket>(int.MaxValue));
                    services.AddSingleton<MessageHandler>((_ =>
                    {
                        var handler = new Network.Server.Node.Generated.GeneratedMessageHandler();
                        handler.Initialize();
                        return handler;
                    }));

                    services.AddSingleton<ActorMessageFactory>();
                    services.AddSingleton<IActorManager, ActorManager>();
                    services.AddNodeController<TestController>();
                    services.AddNodeController<StopTestController>();
                    services.AddSingleton<NodeCommunicator>();

                    services.AddSingleton<NodeEventController, StatelessEventController>();
                    services.AddSingleton<NodePacketHandler>();
                    services.AddSingleton<INodeSender, NodeSender>();
                    services.AddSingleton<INodeResponser, NodeResponser>();

                    services.Configure<NodeConfig>(options =>
                    {
                        options.RedisConnectionString = redisConnectionString;
                        options.ServerRegistryKey = "test-servers";
                        options.ServerType = serverType;
                        options.SubApiName = apiName;
                   //     options.HandShakeTimeoutMs = 20000;
                        options.HandShakeTimeoutMs = 200_0000;
                        //options.HeartBeatTtlSeconds = 30000;
                        options.NodeGuid = Guid.NewGuid();
                        options.Port = Interlocked.Increment(ref _portIndex);
                    });

                });

            var host = await hostBuilder.StartAsync();

            var manager = host.Services.GetRequiredService<INodeManager>();
            var nodeSender = host.Services.GetRequiredService<INodeSender>();
            var node = host.Services.GetRequiredService<NodeService>();

            _ = host.Services.GetRequiredService<NodePacketHandler>();


            _hosts.Add(host);
            var networkTestServer = new NetworkTestServer(node, manager, nodeSender);

            if (!_servers.ContainsKey(apiName))
                _servers.Add(apiName, new List<NetworkTestServer>());

            _servers[apiName].Add(networkTestServer);
            return networkTestServer;
        }
        catch (Exception e)
        {
            output?.WriteLine(e.ToString());
            throw;
        }
    }

    public async ValueTask DisposeAsync()
    {
        foreach (var host in _hosts)
        {
            await host.StopAsync();
            host.Dispose();
        }

        _hosts.Clear();
        _servers.Clear();
    }
}