using System.Buffers.Binary;
using Network.Server.Common.Memory;
using Network.Server.Common.Packets;
using Network.Server.Common.Utils;
using Network.Server.Front.Actor;
using NetworkServer.ProtoGenerator;

namespace Network.Server.Front.Core;

 public class PacketParserForClient : IPacketParser<ActorMessage>
{
    public IReadOnlyList<ActorMessage> Parse(ArrayPoolBufferWriter buffer)
    {
        var packets = new List<ActorMessage>();

        while (true)
        {
            // 1. peek total_size
            var span = buffer.WrittenSpan;
            if (span.Length < 4)
                break;

            int totalSize = BinaryPrimitives.ReadInt32LittleEndian(span);
            if (buffer.WrittenCount < totalSize)
                break;

            buffer.ReadAdvance(4); 
            
            var header = new Header();
            header.Flags = (PacketFlags)buffer.ReadByte();
            header.MsgId = buffer.ReadInt32LittleEndian();
            header.MsgSeq = buffer.ReadUInt16LittleEndian();

            if (header.Flags.HasFlagFast(PacketFlags.HasError))
            {
                header.ErrorCode = buffer.ReadUInt16LittleEndian();
            }

            if (header.Flags.HasFlagFast(PacketFlags.Compressed))
            {
                header.OriginalSize = buffer.ReadInt32LittleEndian();

                var compressSize = totalSize - header.GetSize();
                var payload = Lz4Holder.Instance.Decompress(buffer.WrittenSpan.Slice(0, compressSize), header.OriginalSize);
                buffer.ReadAdvance(compressSize);

                var parser = AutoGeneratedParsers.GetParserById(header.MsgId);
                if (parser == null)
                    throw new Exception($"Unknown packet ID: {header.MsgId}");
                
                var message = parser.ParseFrom(payload);
                packets.Add(new ActorMessage(header, message));
            }
            else
            {
                var payloadSize = totalSize - header.GetSize();
                var payload = new byte[payloadSize];
                buffer.CopyTo(payload);
                buffer.ReadAdvance(payloadSize);
                
                var parser = AutoGeneratedParsers.GetParserById(header.MsgId);
                if (parser == null)
                    throw new Exception($"Unknown packet ID: {header.MsgId}");
                
                var message = parser.ParseFrom(payload);
                packets.Add(new ActorMessage(header, message));
            }
        }

        return packets;
    }
}