using System.Buffers.Binary;
using Google.Protobuf;
using Network.Server.Common.Memory;
using Network.Server.Common.Packets;
using Network.Server.Front.Actor;
using NetworkServer.ProtoGenerator;

namespace Network.Server.Front.Core
{
    public sealed class ProtoPacketParser : IPacketParser<ActorMessage>
    {
        public IReadOnlyList<ActorMessage> Parse(ArrayPoolBufferWriter buffer)
        {
            var packets = new List<ActorMessage>();

            while (true)
            {
                // 1. Peek bodySize (LittleEndian)
                var span = buffer.WrittenSpan;
                if (span.Length < 4)
                    break;

                int totalSize = BinaryPrimitives.ReadInt32LittleEndian(span);
                if (buffer.WrittenCount < totalSize)
                    break;

                // 3. Consume actual packet using LittleEndian reads
                buffer.ReadAdvance(4); // bodySize

                var header = new Header
                {
                    Flags = (PacketFlags) buffer.ReadByte(),
                    MsgId = buffer.ReadInt32LittleEndian(),
                    MsgSeq = buffer.ReadUInt16LittleEndian()
                };

                var parser = AutoGeneratedParsers.GetParserById(header.MsgId);
                if (parser == null)
                    throw new Exception($"Unknown packet ID: {header.MsgId}");

                var payloadSize = totalSize - header.GetSize();
                var message = parser.ParseFrom(buffer.GetReadSpan(payloadSize));
                buffer.ReadAdvance(payloadSize);

                if (message == null)
                    throw new Exception($"Packet Parse Failed: {header.MsgId}");

                packets.Add(new ActorMessage(header, message));
            }

            return packets;
        }
    }
}