using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Network.Server.Common;
using Network.Server.Common.Utils;
using Network.Server.Front.Actor;
using Network.Server.Front.Config;
using Network.Server.Front.Core;
using Network.Server.Generated;
using NetworkEngine.Tests.Node;
using NetworkServer.ProtoAutoGen;
using NetworkServer.ProtoGenerator;
using NetworkServer.Sample.Controllers;
using Serilog;
using Serilog.Events;
using StackExchange.Redis;

namespace NetworkServer.Sample;

public class Program
{
    private static ProtoInitializer? _init;

    public static async Task Main(string[] args)
    {
        // Proto 초기화
        _init ??= new AutoGeneratedInitializer();
        _init.Initialize();

        // Configuration 빌드 (Serilog 초기화용)
        var configuration = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
            .AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production"}.json", optional: true, reloadOnChange: true)
            .AddEnvironmentVariables()
            .Build();

        // Serilog 설정 - appsettings.json에서 읽기
        Log.Logger = new LoggerConfiguration()
            .ReadFrom.Configuration(configuration)
            .CreateLogger();

        try
        {
            Log.Information("NetworkServer Sample 시작");

            var host = CreateHostBuilder(args).Build();

            await host.RunAsync();
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "서버 시작 실패");
            throw;
        }
        finally
        {
            await Log.CloseAndFlushAsync();
        }
    }

    private static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .UseServiceProviderFactory(new DefaultServiceProviderFactory(new ServiceProviderOptions
            {
                ValidateOnBuild = true // 빌드 시 모든 싱글톤 즉시 생성
            }))
            .UseSerilog()
            .ConfigureServices((context, services) =>
            {
                var configuration = context.Configuration;

                // FrontServer 등록
                services.AddHostedService<FrontServer>();

                // Redis 연결 (InGameConnectionQueue용) - appsettings.json에서 읽기
                var redisConnectionString = configuration["Redis:InGameConnectionQueue:ConnectionString"] ?? "localhost:6379";
                var redisConnectTimeout = configuration.GetValue<int>("Redis:InGameConnectionQueue:ConnectTimeout", 5000);
                var redisSyncTimeout = configuration.GetValue<int>("Redis:InGameConnectionQueue:SyncTimeout", 5000);
                var redisAbortOnConnectFail = configuration.GetValue<bool>("Redis:InGameConnectionQueue:AbortOnConnectFail", false);

                services.AddKeyedSingleton<IConnectionMultiplexer>(
                    "InGameConnectionQueue",
                    ConnectionMultiplexer.Connect(new ConfigurationOptions
                    {
                        EndPoints = { redisConnectionString },
                        AbortOnConnectFail = redisAbortOnConnectFail,
                        ConnectTimeout = redisConnectTimeout,
                        SyncTimeout = redisSyncTimeout
                    }));

                // 클러스터 핵심 서비스 등록
                services.AddSingleton<UniqueIdGenerator>(_ => new UniqueIdGenerator(Guid.NewGuid()));
                services.AddSingleton<IApplicationStopper, HostApplicationStopper>();
                services.AddSingleton<IInGameConnectionQueue, InGameConnectionQueue>();
                services.AddSingleton<TimeProvider>(_ => TimeProvider.System);

                // 핸들러 등록
                services.AddHandler();

                // Actor 관리자 등록
                services.AddSingleton<IActorManager, ActorManager>();

                // 샘플 컨트롤러 등록
                services.AddSingleton<SampleController>();

                // FrontServer 설정 - appsettings.json에서 읽기
                services.Configure<FrontServerConfig>(configuration.GetSection("FrontServerConfig"));
            });
}
