using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Network.Server.Common;
using Network.Server.Common.Utils;
using Network.Server.Tcp.Actor;
using Network.Server.Tcp.Config;
using Network.Server.Tcp.Core;
using Network.Server.Generated;
using NetworkServer.ProtoAutoGen;
using NetworkServer.ProtoGenerator;
using NetworkServer.Sample.Controllers;
using Serilog;
using Serilog.Events;
using Network.Server.Tcp.Extensions;

namespace NetworkServer.Sample;

public class Program
{
    private static ProtoInitializer? _init;

    public static async Task Main(string[] args)
    {
        // Proto 초기화
        _init ??= new AutoGeneratedInitializer();
        _init.Initialize();

        // Configuration 빌드 (Serilog 초기화용)
        var configuration = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
            .AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production"}.json", optional: true, reloadOnChange: true)
            .AddEnvironmentVariables()
            .Build();

        // Serilog 설정 - appsettings.json에서 읽기
        Log.Logger = new LoggerConfiguration()
            .ReadFrom.Configuration(configuration)
            .CreateLogger();

        try
        {
            Log.Information("NetworkServer Sample 시작");

            var host = CreateHostBuilder(args).Build();

            await host.RunAsync();
            
            Log.Information("NetworkServer Sample 종료");
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "서버 시작 실패");
            throw;
        }
        finally
        {
            await Log.CloseAndFlushAsync();
        }
    }

    private static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .UseServiceProviderFactory(new DefaultServiceProviderFactory(new ServiceProviderOptions
            {
                ValidateOnBuild = true // 빌드 시 모든 싱글톤 즉시 생성
            }))
            .UseSerilog()
            .ConfigureServices((context, services) =>
            {
                var configuration = context.Configuration;

                // TcpServer 및 관련 Core 서비스 등록 (확장 메서드 사용)
                services.AddTcpServer<InGameConnectionQueue>(configuration);
                
                
                // 샘플 컨트롤러 등록
                services.AddSingleton<SampleController>();
            });
}
