using System.Diagnostics;
using Google.Protobuf;
using Microsoft.Extensions.Options;
using Network.Server.Common.Packets;
using Network.Server.Node.Config;
using Network.Server.Node.Core;
using Network.Server.Node.Utils;
using NetworkServer.ProtoGenerator;

namespace Network.Server.Node.Network;

public class NodeSender(
    IOptions<NodeConfig> nodeConfig,
    INodeManager nodeManager,
    RequestCache<InternalPacket> requestCache,
    NodeCommunicator nodeCommunicator)
    : INodeSender
{
    private NodeConfig NodeConfig { get; } = nodeConfig.Value;

    public Task<TResponse> RequestApiAsync<TRequest, TResponse>(long actorId, string apiName,
        TRequest request)
        where TRequest : IMessage<TRequest>, new()
        where TResponse : IMessage<TResponse>, new()
    {
        var targetNode = nodeManager.RoundRobinByApiName(apiName);
        if (targetNode is null || targetNode.IsClose)
            throw new Exception($"Failed to find target node apiName:{apiName}");

        return RequestInternalAsync<TRequest, TResponse>(actorId, targetNode, request);
    }

    public Task<TResponse> RequestApiAsync<TRequest, TResponse>(string apiName, TRequest request) 
        where TRequest : IMessage<TRequest>, new() 
        where TResponse : IMessage<TResponse>, new()
    {
        return RequestApiAsync<TRequest, TResponse>(InternalPacket.ServerActorId, apiName, request);
    }

    public Task<TResponse> RequestAsync<TRequest, TResponse>(long actorId, long nodeId, TRequest request)
        where TRequest : IMessage<TRequest>, new()
        where TResponse : IMessage<TResponse>, new()
    {
        var targetNode = nodeManager.FindNode(nodeId);
        if (targetNode is null || targetNode.IsClose)
            throw new Exception($"Failed to find target node {nodeId}");

        return RequestInternalAsync<TRequest, TResponse>(actorId, targetNode, request);
    }

    private async Task<TResponse> RequestInternalAsync<TRequest, TResponse>(long actorId, RemoteNode targetNode,
        TRequest message)
        where TRequest : IMessage<TRequest>, new()
        where TResponse : IMessage<TResponse>, new()
    {
        var requestKey = requestCache.GetRequestKey();

        var packet = InternalPacket.Create(actorId, NodeConfig.NodeId, targetNode.Identity, requestKey, false, message);

        var responseTask = requestCache.PendingAsync(requestKey);
        nodeCommunicator.Send(targetNode.IdentityBytes, packet);
        using var response = await responseTask;

        var parser = AutoGeneratedParsers.GetParserById(response.MsgId);
        Debug.Assert(parser != null);

        return (TResponse) parser.ParseFrom(response.Payload);
    }
}