using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using NetworkServer.ProtoGenerator;

namespace Network.Server.Node.Network;

public class RoutingPackageOptions
{
    public List<(string PackageName, string ApiName)> Mappings { get; } = new();
}

public class GatewayPackageMapping
{
    public GatewayPackageMapping(IOptions<RoutingPackageOptions> options)
    {
        foreach (var (packageName, serverName) in options.Value.Mappings)
        {
            RegisterPackageMapping(packageName, serverName);
        }
    }

    private readonly Dictionary<string, string> _packageMapping = new();

    void RegisterPackageMapping(string packageName, string serverName) =>
        _packageMapping.Add(packageName, serverName);

    public string GetApiNameByPackageName(string packageName) =>
        _packageMapping.GetValueOrDefault(packageName) ?? string.Empty;

    public bool IsContainsPackageName(string packageName) => _packageMapping.ContainsKey(packageName);
    
    public string GetApiNameByMsgId(int msgId) => AutoGeneratedParsers.GetPackageNameById(msgId);

}