using Google.Protobuf;
using Network.Server.Common.Packets;
using NetworkServer.ProtoGenerator;

namespace Network.Server.Tcp.Core;

public class Response(IMessage message, Header header)
{
    public IMessage Message { get; set; } = message;
    public Header Header { get; set; } = header;

    public static Response Ok(IMessage message, ushort requestId = 0, PacketFlags flags = PacketFlags.None)
    {
        Header header = new Header
        {
            MsgId = AutoGeneratedParsers.GetIdByInstance(message),
            RequestId = requestId,
            ErrorCode = 0,
            Flags = flags
        };

        return new Response(message, header);
    }

    public static Response Error(ushort errorCode, IMessage message, ushort requestId = 0, PacketFlags flags = PacketFlags.None)
    {
        Header header = new Header
        {
            MsgId = AutoGeneratedParsers.GetIdByInstance(message),
            RequestId = requestId,
            ErrorCode = errorCode,
            Flags = flags.AddFlag(PacketFlags.HasError)
        };

        return new Response(message, header);
    }
}