using Google.Protobuf;


namespace Internal.Protocol
{
    public sealed partial class ServerInfo
    {
        public const int MsgId = 0;
    }

    public sealed partial class NodeHandShakeReq
    {
        public const int MsgId = 1;
    }

    public sealed partial class NodeHandShakeRes
    {
        public const int MsgId = 2;
    }

    public sealed partial class DefaultCreatePacketReq
    {
        public const int MsgId = 3;
    }

    public sealed partial class DefaultCreatePacketRes
    {
        public const int MsgId = 4;
    }
}

namespace NetworkServer.ProtoGenerator
{
    /// <summary>
    /// Protobuf 메시지 ID 매핑 관리 (AOT 호환)
    /// Source Generator가 생성한 IParserRegistration 구현체를 통해 등록됩니다
    /// Initialize() 메서드는 Source Generator가 자동 생성합니다
    /// </summary>
    ///
    ///
    public abstract class ProtoInitializer
    {
        protected bool Initialized = false;

        public virtual void Initialize()
        {
            AutoGeneratedParsers.Register(
                Internal.Protocol.ServerInfo.MsgId,
                Internal.Protocol.ServerInfo.Parser,
                Internal.Protocol.ServerInfo.Descriptor.FullName,
                "Internal.Protocol");

            AutoGeneratedParsers.Register(
                Internal.Protocol.NodeHandShakeReq.MsgId,
                Internal.Protocol.NodeHandShakeReq.Parser,
                Internal.Protocol.NodeHandShakeReq.Descriptor.FullName,
                "Internal.Protocol");

            AutoGeneratedParsers.Register(
                Internal.Protocol.NodeHandShakeRes.MsgId,
                Internal.Protocol.NodeHandShakeRes.Parser,
                Internal.Protocol.NodeHandShakeRes.Descriptor.FullName,
                "Internal.Protocol");
            
            AutoGeneratedParsers.Register(
                Internal.Protocol.DefaultCreatePacketReq.MsgId,
                Internal.Protocol.DefaultCreatePacketReq.Parser,
                Internal.Protocol.DefaultCreatePacketReq.Descriptor.FullName,
                "Internal.Protocol");
            
            AutoGeneratedParsers.Register(
                Internal.Protocol.DefaultCreatePacketRes.MsgId,
                Internal.Protocol.DefaultCreatePacketRes.Parser,
                Internal.Protocol.DefaultCreatePacketRes.Descriptor.FullName,
                "Internal.Protocol");
        }
    }

    public static class AutoGeneratedParsers
    {
        private static readonly Dictionary<int, MessageParser> IdToParserMap = new();
        private static readonly Dictionary<int, string> IdToPackageMap = new();
        private static readonly Dictionary<string, int> FullNameToIdMap = new();

        /// <summary>
        /// 메시지 타입을 등록합니다
        /// </summary>
        /// <param name="id">메시지 ID</param>
        /// <param name="parser">메시지 파서</param>
        /// <param name="fullName">메시지 전체 이름 (Descriptor.FullName)</param>
        /// <param name="packageName">패키지 이름 (예: "proto.test")</param>
        public static void Register(int id, MessageParser parser, string fullName, string packageName)
        {
            IdToParserMap[id] = parser;
            IdToPackageMap[id] = packageName;
            FullNameToIdMap[fullName] = id;
        }


        /// <summary>
        /// 등록 초기화 (테스트용)
        /// </summary>
        public static void Clear()
        {
            IdToParserMap.Clear();
            IdToPackageMap.Clear();
            FullNameToIdMap.Clear();
        }

        #region Lookup Methods

        /// <summary>
        /// ID로 MessageParser를 가져옵니다
        /// </summary>
        public static MessageParser? GetParserById(int id)
            => IdToParserMap.GetValueOrDefault(id);

        /// <summary>
        /// ID로 패키지 이름을 가져옵니다
        /// </summary>
        public static string GetPackageNameById(int id)
            => IdToPackageMap.GetValueOrDefault(id, string.Empty);


        public static int GetIdByInstance(IMessage message)
        {
            return FullNameToIdMap.GetValueOrDefault(message.Descriptor.FullName, -1);
        }

        #endregion
    }
}