using Google.Protobuf;

namespace NetworkServer.ProtoGenerator
{
    /// <summary>
    /// Protobuf 메시지 ID 매핑 관리 (AOT 호환)
    /// Source Generator가 생성한 IParserRegistration 구현체를 통해 등록됩니다
    /// Initialize() 메서드는 Source Generator가 자동 생성합니다
    /// </summary>
    ///
    ///
    public abstract class ProtoInitializer
    {
        protected abstract void Initialize();
    }

    public static class AutoGeneratedParsers
    {
        private static readonly Dictionary<int, MessageParser> IdToParserMap = new();
        private static readonly Dictionary<int, string> IdToPackageMap = new();
        private static readonly Dictionary<string, int> FullNameToIdMap = new();

        /// <summary>
        /// 메시지 타입을 등록합니다
        /// </summary>
        /// <param name="id">메시지 ID</param>
        /// <param name="parser">메시지 파서</param>
        /// <param name="fullName">메시지 전체 이름 (Descriptor.FullName)</param>
        /// <param name="packageName">패키지 이름 (예: "proto.test")</param>
        public static void Register(int id, MessageParser parser, string fullName, string packageName)
        {
            IdToParserMap[id] = parser;
            IdToPackageMap[id] = packageName;
            FullNameToIdMap[fullName] = id;
        }


        /// <summary>
        /// 등록 초기화 (테스트용)
        /// </summary>
        public static void Clear()
        {
            IdToParserMap.Clear();
            IdToPackageMap.Clear();
            FullNameToIdMap.Clear();
        }

        #region Lookup Methods

        /// <summary>
        /// ID로 MessageParser를 가져옵니다
        /// </summary>
        public static MessageParser? GetParserById(int id)
            => IdToParserMap.GetValueOrDefault(id);

        /// <summary>
        /// ID로 패키지 이름을 가져옵니다
        /// </summary>
        public static string GetPackageNameById(int id)
            => IdToPackageMap.GetValueOrDefault(id, string.Empty);


        public static int GetIdByInstance(IMessage message)
        {
            return FullNameToIdMap.GetValueOrDefault(message.Descriptor.FullName, -1);
        }

        #endregion
    }
}