using Network.Server.Common;
using Network.Server.Common.Packets;
using NetworkServer.ProtoGenerator;

namespace Network.Server.Node.Core;

public class ActorMessageFactory
{
    public virtual ActorMessage? Create(InternalPacket packet)
    {
        var parser = AutoGeneratedParsers.GetParserById(packet.MsgId);
        if (parser == null)
            return null;

        try
        {
            var msg = parser.ParseFrom(packet.Payload);
            return new ActorMessage(packet.Header, msg);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
    }
}