using Google.Protobuf;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using NetworkClient;
using NetworkClient.Config;
using NetworkServer.ProtoAutoGen;
using Proto;
using Proto.Test;

namespace TestClient.Proto;

public class TestClient
{
	private readonly IClientEvent _clientEvent;
	private NetClient? _netClient;
	private readonly TestClientMessageHandler _messageHandler;
	private readonly ILogger<TestClient> _logger;

	public TestClient(IClientEvent clientEvent, ILogger<TestClient> logger)
	{
		new AutoGeneratedInitializer().Initialize();
		
		_clientEvent = clientEvent;

		// Logger 설정
		_logger = logger;
		
		// MessageHandler 설정
		_messageHandler = new TestClientMessageHandler();
		_messageHandler.OnMessageReceived += OnReceive;
		_messageHandler.Initialize();
	}

	private void OnDisconnect()
	{
		_clientEvent.OnDisconnect();
	}

	private void OnConnect(bool result)
	{
		_clientEvent.OnConnect(result);
	}

	public async Task<bool> ConnectAsync(string ip, int port)
	{
		// 기존 연결이 있으면 정리
		_netClient?.Dispose();
		
		// NetClient 생성
		_netClient = new NetClient(ip, port, _logger, _messageHandler);
		_netClient.OnConnect += OnConnect;
		_netClient.OnDisconnect += OnDisconnect;

		return await _netClient.ConnectAsync();
	}

	private void OnReceive(IMessage packet)
	{
		var multilineText = JsonConvert.SerializeObject(packet, Formatting.Indented);
		_clientEvent.PrintLog($"{packet.Descriptor.Name} {Environment.NewLine} {multilineText}");
	}

	public void Send(IMessage message)
	{
		_netClient?.Send(message);
	}

	public void Update()
	{
		_netClient?.Update();
	}

	public bool IsConnected() => _netClient?.State == ClientState.Connected;

	public async Task<TResponse> RequestAsync<TResponse>(IMessage request)
		where TResponse : IMessage
	{
		if (_netClient == null)
			throw new InvalidOperationException("NetClient is not initialized. Call ConnectAsync first.");

		return await _netClient.RequestAsync<TResponse>(request);
	}
	
	
	public async Task<IMessage> RequestAsync(IMessage request)
	{
		if (_netClient == null)
			throw new InvalidOperationException("NetClient is not initialized. Call ConnectAsync first.");

		return await _netClient.RequestAsync(request);
	}

	public async Task<bool> LoginAsync(string platformUid, EAccountPlatform platform, string token, ERegionCode regionCode)
	{
		if (_netClient == null)
			throw new InvalidOperationException("NetClient is not initialized. Call ConnectAsync first.");

		return true;
	}

	public void Disconnect() => _netClient?.DisconnectClient();
}